services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,ecs,iam,logs,s3,elasticloadbalancing,application-autoscaling,cloudwatch
      - DEFAULT_REGION=us-east-1
      - DEBUG=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
